# Generated by Django 5.0.14 on 2026-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
